language: cpp

matrix:
  include:
    - os: linux
      sudo: true
      dist: trusty
    - os: osx
      sudo: false

env:
  global:
    - secure: "AXHFIafTmbGDsHD3mUVj5a4I397DQjti/WoqAJGUp2PglxTcc04BwxZ9Z+xLuf5N2Hs5r9ojAJLT8OGxJCLBDXzneQTNSqXbFuYSLbqrEAiIRlA9eRIotWCg+wYcO+5e8MKX+cHVKwiIWasUB21AtCdq6msh6Y3pUshZp212VPg="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: ppa:beineri/opt-qt551-trusty
      - sourceline: deb http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu/ trusty main
    packages:
      - gcc-6
      - g++-6
      - qt55base
      - xorg-dev
      - lib32stdc++6 # For CMake
      - lftp # To upload builds

install: ./.travis-deps.sh
script: ./.travis-build.sh
after_success: ./.travis-upload.sh
